name: cinebox
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Riverpod estável e compatível com code generation
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17

  # Outras dependências do projeto
  envied: ^1.2.0
  retrofit: ^4.6.0
  logger: ^2.6.0
  json_annotation: ^4.9.0
  dio: ^5.9.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Build tools
  build_runner: ^2.4.9
  riverpod_generator: ^3.0.0-dev.17

  # Optional, mantém custom_lint se você usa regras personalizadas
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0-dev.17

  # Outros geradores que você mencionou
  envied_generator: ^1.2.0
  retrofit_generator: ^10.0.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/images/a_dot_ham.jpeg
